spring:
  application:
    name: JTSB01
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./h2/db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
  devtools:
    restart:
      enabled: false