spring:
  application:
    name: JTSB01
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console  # 프로덕션 환경에서 사용할 H2 콘솔 경로
  devtools:
    restart:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub


#logging:
#  level:
#    root: INFO
#    org.example: DEBUG
#  file:
#    name: app.log

---
# 기본 설정 (테스트용 메모리 H2 DB)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1  # 메모리 DB 사용
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# 프로덕션 설정 (실제 DB)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:./h2/db  # 파일 기반 H2 DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false